package game.logic;

public enum Situation {
    AWAITS_START, AWAITS_COLUMN_CHOICE, AWAITS_EXIT, AWAITS_GAME_MODE, AWAITS_MATH_MINI_GAME,AWAITS_MINI_GAME,AWAITS_NEXT_REPLAY_MOVE,AWAITS_PLAYER_NAME,AWAITS_REPLAY_ID,AWAITS_THE_NEXT_MOVE,AWAITS_WRITING_MINI_GAME
}
